### ISSUE TITLE
Improve the quality of the code 

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/Social-Platform-Donut#100]
Quality of the code can be improved by -
1. linting the code
2. Optimise the mongoose query 
3. use of es6 
4. Added prettier to pretify the code .

**Comment by Rupeshiya** [comment]
@jaskirat2000 ,Should I work on this ??

**Comment by debck** [comment]
@Rupeshiya 👍 you can start working on it. In case you need any help ask in the slack group.
