### ISSUE TITLE
Track memory leakage of this Node.js application

### ISSUE THREAD

**Issue by TG1999** [codeuino/Social-Platform-Donut#107]

**Comment by lakshyabatman** [comment]
Please describe the problem.

**Comment by TG1999** [comment]
Memory leaks often go unnoticed. They become a problem when someone pays extra attention to the production performance metrics.
So if we can track or take log of memory leakage we can cover those.
And hence can scale this application

**Comment by TG1999** [comment]
![screenshot 2019-03-04 at 5 24 59 pm](https://user-images.githubusercontent.com/34160672/53732157-02424680-3ea3-11e9-8673-328b0bf3231e.png)
screenshot related to stats of the application

**Comment by lakshyabatman** [comment]
Ok, can you add some links so one can actually understand where these memory leaks occur and you can even solve the issue :)

**Comment by TG1999** [comment]
https://nodejs.org/en/docs/guides/simple-profiling/ here is the link for everyone issue and I will also suggest that there should be some rule added in README that no one's code shouldn't increase the memory leakage of the application

**Comment by TG1999** [comment]
Now you can review the PR and merge it in development branch

**Comment by TG1999** [comment]
@jaskirat2000 the issue has been solved please review the PR.
