### ISSUE TITLE
modify readme

### ISSUE THREAD

**Issue by gabru-md** [codeuino/Social-Platform-Donut#11]
modifying readme a bit.
There are a lot fo `npm install` commands. All this can be done by simplying typing `npm install` inside the directory of the project. So a simple change in readme can make it cleaner. :D

This issue can be taken up by anyone.
Cheers!

**Comment by ChameeraD** [comment]
Can I try

**Comment by jaskirat2000** [comment]
Sure go on

**Comment by jaskirat2000** [comment]
@ChameeraD sure please go on and try to provide better readme with pro[er installation, running in the form of videos
