### ISSUE TITLE
making the PR template

### ISSUE THREAD

**Issue by iamgrawal** [codeuino/Social-Platform-Donut#110]
A proper template is to be followed for making a Pull Request on any issue. Please provide a template for the same.

**Comment by jaskirat2000** [comment]
As well as issue template

**Comment by lakshyabatman** [comment]
Please share the template before merging so we call can have look and I suggest to add a comment for asking the contributor to add gif for the issue or the pull request.

**Comment by iamgrawal** [comment]
@jaskirat2000 @lakshyabatman Sure

**Comment by jaskirat2000** [comment]
I think this looks fine to me https://gist.github.com/indiesquidge/85075be518631964a56b75946153ebbf

**Comment by jaskirat2000** [comment]
### **Problem**
 _Describe the problem you are trying to achieve. Please provide in detail_ 

### **Solution of problem**
_How did you solve this problem? Please provide in detail_

### **Before and After Screenshots**
**Before** [How was it earlier, add it here]
**After** [How it looks now, add it here]

### **Type of Change**
- [ ] Bug fix
- [ ] New Feature 
- [ ] Development of UI/UX prototypes
- [ ] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [ ] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation 
- [ ] I have updated the Readme accordingly
- [ ] I made PR within **development branch only**

**Comment by jaskirat2000** [comment]
Does the above I wroylte make sense ? @iamgrawal @lakshyabatman @devshiva619

**Comment by jaskirat2000** [comment]
@shivamluthra

**Comment by iamgrawal** [comment]
@jaskirat2000 Yeah, looks good

**Comment by devshiva619** [comment]
@jaskirat2000 👍

**Comment by iamgrawal** [comment]
I am closing this issue, since a PR has been for this.

**Comment by iamgrawal** [comment]
There is an update that is needed in the template, so reopening this issue.
