### ISSUE TITLE
Make Issue template

### ISSUE THREAD

**Issue by jaskirat2000** [codeuino/Social-Platform-Donut#115]

**Comment by iamgrawal** [comment]
@jaskirat2000 you haven't mentioned anything in the description.

**Comment by jaskirat2000** [comment]
I thought lets others put their thoughts

**Comment by jaskirat2000** [comment]
### **Description of the problem**
_Describe the issue in detail_

### **How to solve**
_Explain the issue how it can be solved in detail with links if required

### **Expected Outcome**
_What will be the result_

**Comment by jaskirat2000** [comment]
@iamgrawal

**Comment by jaskirat2000** [comment]
### **Screenshot**
_Add Screenshot to explain things better_

**Comment by devshiva619** [comment]
@jaskirat2000 perfect 👍

**Comment by iamgrawal** [comment]
@jaskirat2000 since you are the owner of this repo, you only can setup the issue template for this repo. For reference you can go to this link: https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by iamgrawal** [comment]
Since the issue template is created, I am closing this issue.
