### ISSUE TITLE
Login Page For User

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#117]
We need a proper login page for users which redirects them to dashboard.
Assigning it to myself

**Comment by nik72619c** [comment]
Sorry to write it in this comment but didn't wanted to create a separate issue:-
How to be a part of this organisation...kindly guide me with this!
I'm already an OSS contributor and maintainer, hence wish to contribute and help :)
@lakshyabatman

**Comment by jaskirat2000** [comment]
Why don't you join us at slack.codeuino.org

**Comment by nik72619c** [comment]
Sure... will join right away

**Comment by arghac14** [comment]
@lakshyabatman are you still working on this?

**Comment by lakshyabatman** [comment]
@arghac14 , yes I  am.
