### ISSUE TITLE
Adding some task runner like grunt or gulp

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#118]
Having large css, js and images files can decrease performance alot, so adding task runners like gulp or grunt can help alot by minifying js and css files and reducing image sizes.

The disribution version of project will be created and will be added to dist folder which can be used in production stage. 

Assigning this issue to myself.

**Comment by Rupeshiya** [comment]
@lakshyabatman are you working on this?

**Comment by lakshyabatman** [comment]
Yes,  I was working on this, but due to poor structure of workflow , I kept this issue on hold :)
