### ISSUE TITLE
signup route and page for the user

### ISSUE THREAD

**Issue by mark-nakachon** [codeuino/Social-Platform-Donut#122]
there is a signup page in the codebase but it is not used in the homepage and even a route is not there for signup

I will solve this issue by providing a route /signup and I will add style and store the details in MongoDB
and now the user can log in (there is no page for login also but #117 is already reported) 

after resolving this issue a user can signup

**Comment by jaskirat2000** [comment]
This issue would not be acceptable unless you follow issue template. It would be closed soon if it is not made accordingly

**Comment by lakshyabatman** [comment]
There exist a page for signup.
