### ISSUE TITLE
Feeback page exists in separate folder in views

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#124]
### **Description of the problem**
In the views folder, there is another folder for feedback, which is disrupting the flow of codebase.

### **How to solve**
Please change all routes related to feedback and add all css and js files to css and js folder respectively.

### **Screenshot**
none

### **Expected Outcome**
Better codebase

**Comment by nik72619c** [comment]
Anybody working on this?

**Comment by nurdtechie98** [comment]
I would like to work on this issue

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by lakshyabatman** [comment]
Also make sure the forum folder is also adjusted to views folder

**Comment by lakshyabatman** [comment]
And make it quick, cause I want to automate the project using gulp so I need it urgently

**Comment by lakshyabatman** [comment]
#118

**Comment by nurdtechie98** [comment]
Yes I'll make it by tonight.

**Comment by nurdtechie98** [comment]
@lakshyabatman even the forums folder is present inside a separate folder should I even move that out?

**Comment by lakshyabatman** [comment]
no, thankyou. :)

**Comment by nurdtechie98** [comment]
@lakshyabatman @jaskirat2000 this can be closed now right?

**Comment by jaskirat2000** [comment]
Yes
