### ISSUE TITLE
Implementing ElasticSearch with MongoDB

### ISSUE THREAD

**Issue by TG1999** [codeuino/Social-Platform-Donut#133]
### **Description of the problem**
ElasticSearch implements a lot more features, such as custom splitting of text into words, custom stemming, facetted search and a whole lot more. While MongoDB's (rather simple) text search does some of this, it is not nearly as powerful as ElasticSearch.

If all you ever do is look for a single string in a single field, then MongoDB's normal query system will work excellently for that. If you need to look for words in multiple fields, then MongoDB's text search will work. If you need anything more than that, ElasticSearch is the way to go.

### **How to solve**
By using any module that can index mongoDB documents in ElasticSearch which can be later used to  visualize the data using Kibana https://code.likeagirl.io/5-different-ways-to-synchronize-data-from-mongodb-to-elasticsearch-d8456b83d44f

### **Expected Outcome**
All the data of MongoDB is synced with ElasticSearch

**Comment by TG1999** [comment]
I assign this issue to myself

**Comment by iamgrawal** [comment]
Hey @TG1999 , thanks for this issue. Seeing the scale of the project right now, I don't see any use case of integrating elastic search right now. If you feel like there is a use case then do tell us, there might be the case which could have been skipped by me.

**Comment by TG1999** [comment]
Fine @iamgrawal so should I close this issue for now ? and one thing more can I write a Dockerfile for this project so I can open an issue for the same and start working.

**Comment by iamgrawal** [comment]
@TG1999 thanks for the suggestion for adding the docker file, but since the project is not too big right now so you don't need it. It will be added in the timeline when the project scales.
I am closing this issue since there is no use case as of now, will reopen it whenever we feel to use it.
