### ISSUE TITLE
CSS isn't loading

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#137]
### **Description of the problem**
CSS isn't loading in other-landing.ejs files,

### **How to solve**
Check the integration of css file in the file, as in localhost in the css isn't loading but opening ejs file, it loads.

### **Screenshot**
![Screenshot from 2019-03-09 11-16-34](https://user-images.githubusercontent.com/29687362/54066816-dafdc780-425c-11e9-91cd-bc97c9a9358b.png)
![Screenshot from 2019-03-09 11-16-37](https://user-images.githubusercontent.com/29687362/54066817-db965e00-425c-11e9-9ad8-8b204ff437a8.png)

### **Expected Outcome**
Proper integration of css files.

**Comment by TG1999** [comment]
Assign this issue to me

**Comment by TG1999** [comment]
please review #138 @jaskirat2000

**Comment by lakshyabatman** [comment]
@TG1999 Great job. :)

**Comment by shivamluthra** [comment]
Issue status? @lakshyabatman Can you please close this if it's resolved now?
