### ISSUE TITLE
Why External Bootstrap files is there in other.landing.ejs

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#139]
### **Description of the problem**
In other-landing.ejs, the bootstrap css files is linked to external cdns

### **How to solve**
Add css files in the vendors and integrate it in.

### **Expected Outcome**
Less fetching time of css.

**Comment by lakshyabatman** [comment]
I'm assigning to myself

**Comment by lakshyabatman** [comment]
#140

**Comment by jaskirat2000** [comment]
Sure

**Comment by lakshyabatman** [comment]
@jaskirat2000 , there are other several external cdn link and I'm removing them, okay

**Comment by jaskirat2000** [comment]
Okay,
