### ISSUE TITLE
Add 404 page 

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/Social-Platform-Donut#142]
### **Description of the problem**
_404 page is not rendering on uncaught request_

### **How to solve**
_Add 404 page and render on uncaught request_

### **Expected Outcome**
_On uncaught request 404 page will be rendered_

@jaskirat2000  should I add this ??

**Comment by ayush9898** [comment]
Can I solve this ?

**Comment by jaskirat2000** [comment]
Sure

**Comment by Rupeshiya** [comment]
@ayush9898 it's already fixed ! .

**Comment by prateekiiest** [comment]
I am closing this since its already solved by #148
