### ISSUE TITLE
Audit old packages in package.json

### ISSUE THREAD

**Issue by shivamluthra** [codeuino/Social-Platform-Donut#159]
### **Description of the problem**
_Audit old vulnerable packages in package.json_
_Also update credentials for local mongoDB setup_

### **How to solve**
_```npm audit fix``` automatically fixes most of the vulnerabilities automatically. Remaining ones can be audited manually_
_Update config/credential.js with local mongodb url which was messed up while rebasing old code_

### **Screenshot**
_N/A_

### **Expected Outcome**
_package.json, package-lock.json updated with latest version of packages_
_credential.js updated with local mongodb url for hassle-free db setup_

**Comment by shivamluthra** [comment]
I've fixed this locally and will be sending a PR regarding the same.

**Comment by prateekiiest** [comment]
PR #160 for this issue.

**Comment by prateekiiest** [comment]
Closed by #160
