### ISSUE TITLE
auth/login route not working

### ISSUE THREAD

**Issue by TG1999** [codeuino/Social-Platform-Donut#165]
### **Description of the problem**
I was writing unit tests for routes login route is not working properly

### **How to solve**
There is some error with data.compare() please check

### **Expected Outcome**
The post request should log in user

**Comment by Rupeshiya** [comment]
It's working @TG1999 , have you checked on running locally ?

**Comment by TG1999** [comment]
Yes @Rupeshiya

**Comment by TG1999** [comment]
Can you send a screenshot of the postman or any other tool from which you check your API it will be helpful

**Comment by lakshyabatman** [comment]
Yes, I got an error while logging or signing up using GitHub or google!
![Screenshot from 2019-04-06 22-42-09](https://user-images.githubusercontent.com/29687362/55672833-6058b400-58bd-11e9-9e41-cbe8f6f4f57a.png)
Btw, I was inactive so please enlighten if someone discussed about it :)

**Comment by Rupeshiya** [comment]
Hey @TG1999  @lakshyabatman  working fine in my case.
![login](https://user-images.githubusercontent.com/31209617/55776111-41bf0c80-5ab9-11e9-9f09-be07ad615d93.png)

**Comment by TG1999** [comment]
@Rupeshiya it's /authh/google not /auth/login

**Comment by TG1999** [comment]
I will suggest you to get yourself more familiar to codebase 😃 @Rupeshiya

**Comment by Rupeshiya** [comment]
@TG1999  where you find out /auth/login it's /auth/google or /auth/github .
Have a look then judge anyone .Ok

**Comment by Rupeshiya** [comment]
@TG1999  this is /auth/login . 
![auth](https://user-images.githubusercontent.com/31209617/55776455-71badf80-5aba-11e9-95fc-e723d28e739d.png)

**Comment by TG1999** [comment]
Look in login.routes.js the second last request please check and I am not judging you I was just suggesting you . @Rupeshiya

**Comment by TG1999** [comment]
Bro it's a post request how can you expect a request which will carry password with it can be made get request it is very insecure

**Comment by Rupeshiya** [comment]
Cool !

**Comment by Rupeshiya** [comment]
@TG1999 login with google or github , is fine in your case ?
You are correct it's insecure but I think hashing will be better option here .

**Comment by TG1999** [comment]
Thanks @Rupeshiya for suggestion There is no need to hash it bcrypt is used already I have given the reason in the issue already so please can you see that part it will be really a great help

**Comment by Rupeshiya** [comment]
Sure @TG1999

**Comment by prateekiiest** [comment]
@tharun143 I guess you corrected this in your last merged PR?

**Comment by prateekiiest** [comment]
Should we close this then?

**Comment by TG1999** [comment]
I have not corrected it yet I thought @Rupeshiya is working on it. My bad.

**Comment by Rupeshiya** [comment]
@TG1999 I always assign the issue myself before start working on it, but no worry. You can start working on it.

**Comment by pragun22** [comment]
@TG1999 I can work on this issue if no one is assigned

**Comment by prateekiiest** [comment]
sure @pragun22 go ahead if you want to

**Comment by pragun22** [comment]
I have made a PR for the issue, kindly verify it.
