### ISSUE TITLE
Bugs in Signup Route

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#175]
### **Description of the problem**
There are certain bugs in the signup routes.
Ther signup redirects tot the same page instead of login page or someplace else.

### **How to solve**
Making the route from post to get and then rendering login page after saving data.
### **Expected Outcome**
A working signup route

**Comment by TG1999** [comment]
Are you talking about post request on /auth/userlogin

**Comment by lakshyabatman** [comment]
Yes, btw there was lot of mess in the codeflow although. I have integrated it with the frontend and have you any idea that this route userlogin, saves the data or not?

**Comment by TG1999** [comment]
Let the request be post it will be more secure since we are also saving the password in it we can not let the password be shown in headers.

**Comment by lakshyabatman** [comment]
Yes ofcourse, I will be making some other changes.

**Comment by TG1999** [comment]
Give me some time I will be checking for that btw when I have tested the route it worked and saved the data

**Comment by lakshyabatman** [comment]
#173 , this solves the issue
