### ISSUE TITLE
Header is not appearing

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/Social-Platform-Donut#176]
### **Description of the problem**
_Header is not appearing in submit project section i.e /profile/submitProject_

### **How to solve**
_Add a header or render the same header which is in the home page_

### **Screenshot**

![Screenshot from 2019-04-09 11-38-53](https://user-images.githubusercontent.com/31209617/55777064-65d01d00-5abc-11e9-83fc-e92442deffa8.png)
### **Expected Outcome**
_Header in submit project section i.e /profile/submitProject_

**Comment by sarthak77** [comment]
I guess issues related to frontend should not be dealt with now as it is going to be changed
@iamgrawal

**Comment by lakshyabatman** [comment]
@Rupeshiya you may close this issuse. Thankyou :)
