### ISSUE TITLE
Module for automatically resizing pictures 

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#177]
### **Description of the problem**
**FEATURE UPDATE**
As in #173 and #171, we can upload pictures in DONUT, though users most upload pictures of different size and aspect ratios.
Making the UI bad.
And also, if a user uploads a high-quality image, it might reduce the performance of the app.
### **How to solve**
A module can be created which resize the image to a certain ratio and size.
### **Expected Outcome**
Better User Interface, space optimization, better performance.

I'm assigning this issue to myself and @TG1999 , as we added the profile picture and image feed in the DONUT.

**Comment by MohammadHasham** [comment]
Can I work on this?

**Comment by lakshyabatman** [comment]
I've added a pr of it, it's done :)

**Comment by jaskirat2000** [comment]
Thanks Lakshay, yoir PR will be reviewed soon

**Comment by prateekiiest** [comment]
@lakshyabatman could you link your PR here?

**Comment by lakshyabatman** [comment]
@prateekiiest  #179

**Comment by lakshyabatman** [comment]
PR Merged #179  :)
