### ISSUE TITLE
Introducing JSON Web Tokens for secured API calls

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#180]
### **Description of the problem**
*Feature Suggestion*
There are several requests send to servers for manipulating database and these calls can be misuse which can cause a crash of application and Database.
Example:
 A user cannot manipulate User B's data.
And the simplest and effective way is by using Web Tokens.

### **How to solve**
Installing JWT and updating schema and routes to use JWT
### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
More Secure Application

Note:
This is a really huge feature suggestion as it requires assessment of each routes and implementing JWT in every schema, so I would like to make a separate team for this advancement, @codeuino/contributors please everyone have a look on it.

**Comment by mark-nakachon** [comment]
I will take up this issue

**Comment by lakshyabatman** [comment]
@mark-nakachon , this issue requires the modification in the whole project and I guess only one person cannot take up this issue, let me have talk with the @codeuino/contributors and then we can set up the team for it. Although if you want you can take up the whole project, but just wait for the other members to reply on this. :)
@codeuino/contributors , please have a look on it

**Comment by vaibhavdaren** [comment]
@mark-nakachon  how much time will you require?

**Comment by mark-nakachon** [comment]
@vaibhavdaren currently I have my semester exams I will require a week atleast

**Comment by pragun22** [comment]
@lakshyabatman I am also interested in implementing this. You can count me in for the team.

**Comment by vaibhavdaren** [comment]
> @vaibhavdaren currently I have my semester exams I will require a week atleast

all the best :+1:

**Comment by wildcod** [comment]
I'm intrested to work on this issue
