### ISSUE TITLE
Signup/login page for users showing error of password not matching even when passwords are matching

### ISSUE THREAD

**Issue by pragun22** [codeuino/Social-Platform-Donut#182]
### **Description of the problem**
In the login page for organisations [link](localhost:3000/signup_community.html) even when fields of password and retype password match still it gives an error of password not matching. this occurs because in the file /views/js/signup_validator.js for finding the value of pass and cpass, after writing .getElementByID(), .innerhtml is not written due to which it returns the whole html tag

### **How to solve**
in the file /views/js/signup_validator.js for finding the value of pass and cpass, after writing .getElementByID() also add .innerhtml for getting the entered values

### **Screenshot**
Error screenshot:-
![Screenshot from 2019-04-15 23-53-56](https://user-images.githubusercontent.com/32328935/56156726-77915300-5fdb-11e9-997d-bb406369b38c.png)

### **Expected Outcome**
the page will redirect to whatever it needs to 

I am assigning myself to the issue

**Comment by pragun22** [comment]
#183 made a PR request for the mentioned issue

**Comment by lakshyabatman** [comment]
Hey @pragun22 , can you please close this issue. :)
