### ISSUE TITLE
Contributing.md is not there in the codebase.

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#184]
### **Description of the problem**
Contributing.md doesn't exist.
### **How to solve**
Creation of contribution.md, many new users are getting towards our organization and they might face the problem of where to start.
So a Markdown file describing how to connect with the org and how to start contributing.
This file should consist of a installation guide, interaction with other members, links to resources and description of tags on issues.

### **Screenshot**

![Screenshot from 2019-04-16 20-07-10](https://user-images.githubusercontent.com/29687362/56219213-f80b8e80-6083-11e9-9b37-9e8220ea4bd0.png)

### **Expected Outcome**
Our community will be then up to the standards by Github.

**Comment by prateekiiest** [comment]
sure go ahead

**Comment by lakshyabatman** [comment]
#186 , fixes it @prateekiiest have a look on this :)

**Comment by prateekiiest** [comment]
Thanks @lakshyabatman
