### ISSUE TITLE
User is not defined i.e use.fname and use.lname is not defined in other-landing.ejs

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/Social-Platform-Donut#187]
### **Description of the problem**
_use object is not defined in other-landing.ejs so giving use.lname and use.fname undefined on accessing it. To check the issue go to --> http://localhost:3000/profile/profileview/xyz_

### **How to solve**
_To access the user details by using "use" object should be defined before accessing it_

### **Expected Outcome**
_use.fname and use.lname should render first and last name in other-landing.ejs_

**Comment by lakshyabatman** [comment]
@Rupeshiya , please close this issue as the frontend is migrated to vue, though you can now start contributing in the backend in gsoc branch. Thankyou:)

**Comment by Rupeshiya** [comment]
Great @lakshyabatman , thanks.
