### ISSUE TITLE
Upvote click is sending request to http://localhost:3000/profile/upvote , which is not found.

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/Social-Platform-Donut#188]
### **Description of the problem**
_Upvote click is sending a request to http://localhost:3000/profile/upvote, which does not exist._

### **How to solve**
_It should send request to  http://localhost:3000/profile/upDownVote_

### **Expected Outcome**
_404 error for the request will be removed and like functionality should work properly_

**Comment by lakshyabatman** [comment]
@Rupeshiya , please close this issue, cause We're deleting views folder. Thankyou :)
