### ISSUE TITLE
Frontend Task

### ISSUE THREAD

**Issue by shubham59** [codeuino/Social-Platform-Donut#2]
Need a great UX for the landing page after the user logs in

**Comment by pm17** [comment]
Are you expecting wireframes or a PSD ?

**Comment by jaskirat2000** [comment]
Wire frames

**Comment by Sweta271097** [comment]
Hello,

I would really like to take up this issue.
I'm new to open source and would like contributing!

**Comment by jaskirat2000** [comment]
Sure gk ahead but make sure you should explore the frontend repo also which
is written in the Readme

**Comment by Sweta271097** [comment]
Hello, 

I made new wireframes for the landing page keeping in mind the frontend contents of the previous landing page. Give it a look. I'll make a PR.
![screenshot 49](https://user-images.githubusercontent.com/32592225/50228684-8faaea00-03ce-11e9-95a6-10f664eba656.png)
![screenshot 50](https://user-images.githubusercontent.com/32592225/50228697-93d70780-03ce-11e9-8557-3e88e6198678.png)
![screenshot 51](https://user-images.githubusercontent.com/32592225/50228700-976a8e80-03ce-11e9-8e74-25e515518aa6.png)
![screenshot 52](https://user-images.githubusercontent.com/32592225/50228711-9df90600-03ce-11e9-92ac-4e610269913a.png)
![screenshot 53](https://user-images.githubusercontent.com/32592225/50228715-a0f3f680-03ce-11e9-97d7-6db8692f4f2b.png)

**Comment by jaskirat2000** [comment]
Hey this is so amazing, i like it. And which software you used ?
Also after thiis can you also make up the homepage that is feed page ?
Just ping me once on slack channel.
Looking forward to it.

Thanks
