### ISSUE TITLE
backend mongodb models

### ISSUE THREAD

**Issue by vaibhavdaren** [codeuino/Social-Platform-Donut#207]
### **Description of the problem**
Creation of MongoDB models
1)Creating posts
2)Retrieving al posts
3)Scheduling Posting
4)deleting posts
5)updating posts

### **How to solve**
_Explain the issue how it can be solved in detail with links if required_

### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
_What will be the result_

**Comment by TG1999** [comment]
Assign this issue to me

**Comment by vaibhavdaren** [comment]
@TG1999  populate the issue template

**Comment by TG1999** [comment]
Please close this issue.

**Comment by vaibhavdaren** [comment]
done :package:
