### ISSUE TITLE
Post schema issues

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#217]
### **Description of the problem**
The Post schema has some issues, the user should be an object where ObjectID and type of user should be added.
And User should have posts property for it.
Secondly, can you add a comment of what data to be sent to routes and what response is expected, for frontend developers, please :).
Posts type should be for posts and scholarship only cause there is a different model for projects.
### **How to solve**
Updating schema.

**Comment by lakshyabatman** [comment]
@TG1999 
I am assigning you this. :dagger:

**Comment by Rupeshiya** [comment]
@lakshyabatman are you working on this ?

**Comment by lakshyabatman** [comment]
@Rupeshiya  , yes I solved this :)
