### ISSUE TITLE
Remove Typos from the Readme 

### ISSUE THREAD

**Issue by imdhruvgupta** [codeuino/Social-Platform-Donut#59]
There are few typos in Readme which need to be removed, especially in the "What is Donut?" part.

**Comment by lakshyabatman** [comment]
@imdhruvgupta if this issue is resolved then you can close it :)

**Comment by tharun143** [comment]
I want to take this issue. If it is not closed please reply here ASAP. I will continue the work from March 1st

**Comment by jaskirat2000** [comment]
Sure please go ahead. Looking forward to it.

**Comment by tharun143** [comment]
I will work on this issue from March 1st. Is it okay?

**Comment by jaskirat2000** [comment]
Sure

**Comment by lakshyabatman** [comment]
Also, update the images as well.

**Comment by tharun143** [comment]
Okay

**Comment by tharun143** [comment]
I've done the work. I guess you can close the issue now.

**Comment by tharun143** [comment]
Can I close this issue now?
