### ISSUE TITLE
Add a signup with github and signup with gmail button 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/Social-Platform-Donut#62]
![screenshot from 2019-02-08 19-52-03](https://user-images.githubusercontent.com/37747717/52483921-07c9ab00-2bdb-11e9-82e7-0e36745bb74b.png)
Add a signup button for gmail and github

**Comment by lakshyabatman** [comment]
I can work on it !

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by lakshyabatman** [comment]
#64 , buttons are added! Only integration with their API are left.

**Comment by jaskirat2000** [comment]
Thanks
