### ISSUE TITLE
Readme not updated

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#65]
![screenshot from 2019-02-10 00-05-27](https://user-images.githubusercontent.com/29687362/52525347-50ae5c00-2cce-11e9-9bfb-c315fc59fca6.png)

Screenshots are not updated.

**Comment by jaskirat2000** [comment]
Just improve it. Thanks

**Comment by lakshyabatman** [comment]
#67  @jaskirat2000
