### ISSUE TITLE
Frontend isn't responsive

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#68]
![screenshot from 2019-02-13 22-47-13](https://user-images.githubusercontent.com/29687362/52730516-95ddd100-2fe1-11e9-917d-f374ae2052a4.png)
![screenshot from 2019-02-13 22-47-21](https://user-images.githubusercontent.com/29687362/52730517-95ddd100-2fe1-11e9-8b4b-1534eb881ab6.png)

The codeuino title overflows from the side.

**Comment by jaskirat2000** [comment]
I think these pages are not yet designed for mobile yet. Since it is in the form of software.

**Comment by jaskirat2000** [comment]
@Sweta

**Comment by lakshyabatman** [comment]
@jaskirat2000 software as in? Although, I think making this project mobile friendly would be really good, apart from this the frontend looks perfect . :)

**Comment by NirmalKumarJoshi** [comment]
@lakshyabatman Can I work on this under GSSOC'19. I will integrate bootstrap classes to it.

**Comment by lakshyabatman** [comment]
@NirmalKumarJoshi sure :+1:

**Comment by sarthak77** [comment]
@lakshyabatman I think to make the webpages responsive a complete revamp of original structure is required. It appears to be a time consuming issue which would require a lot of time.
Can I take this up?
It would also be in align with the 3rd project 
Looking for your response
