### ISSUE TITLE
Need a page to submit project

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/Social-Platform-Donut#70]
The route to publish a project is made but no html page is made.
Suggestions for design are appreciated.

**Comment by lakshyabatman** [comment]
@capedcrusader23 you want ejs?

**Comment by capedcrusader23** [comment]
yes

**Comment by lakshyabatman** [comment]
Ok, so can you describe your requirements. @capedcrusader23

**Comment by lakshyabatman** [comment]
@capedcrusader23  I'm taking up this issue!

**Comment by capedcrusader23** [comment]
yes @lakshyabatman,you can work on it

**Comment by lakshyabatman** [comment]
#73 , @capedcrusader23 you can close this issue now! :)

**Comment by capedcrusader23** [comment]
@lakshyabatman  let me test it,if i found it right i will close this issue else we will work on it.

**Comment by lakshyabatman** [comment]
@capedcrusader23 you tested it?

**Comment by lakshyabatman** [comment]
@jaskirat2000 @capedcrusader23 please close this issue, cause I added the submit form page.

**Comment by capedcrusader23** [comment]
yes @lakshyabatman
