### ISSUE TITLE
Needed front end layout for a comments

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/Social-Platform-Donut#72]
![ch](https://user-images.githubusercontent.com/37747717/53124010-5df60100-3580-11e9-9051-d332ed719a58.jpg)
The box below (1,1,comment,share)is simple textarea. Try to improve it and after submitting a comment it should be displayed in a card format.Only focus on design of comment box rather than submit logic.

**Comment by lakshyabatman** [comment]
Yes, I can do it!

**Comment by lakshyabatman** [comment]
#76 , I made some small changes on it!

**Comment by lakshyabatman** [comment]
@capedcrusader23 @jaskirat2000

**Comment by lakshyabatman** [comment]
Please, close this issue as it is done! @jaskirat2000 @capedcrusader23
