### ISSUE TITLE
Want to Contribute to Codeuino

### ISSUE THREAD

**Issue by Yashwanth711** [codeuino/Social-Platform-Donut#74]
Hello Everyone, My name is Yashwanth, from IIT Bhubaneswar,India. I have good knowledge in HTML,CSS, Java Script,Python,Java. I am specialized in Machine Learning,Deep Learning and Data Analytics. I am planning to apply GSOC 2019 with Codeuino.  I need help to get started with. Assign me some task/sub goal to get started to work and contribute codeuino. Thankyou!

**Comment by lakshyabatman** [comment]
Hey @Yashwanth711 , welcome to Codeuino! Please join our slack group to start working with as, and to get started search for begineer's issues in the community and start contributing. :)

**Comment by lakshyabatman** [comment]
Please close this issue asap :)
