### ISSUE TITLE
Not able to scroll in mobile view

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#77]
![screenshot from 2019-02-27 11-16-45](https://user-images.githubusercontent.com/29687362/53468699-425b9080-3a81-11e9-83b8-c9191878a63d.png)

<b>BUG</b>
I cannot scroll over in tablet or mobile view.
Is this some issue or done intentionally for some reason.

<b>I will be taking up this issue</b>

**Comment by jaskirat2000** [comment]
Lakshay we don't need for mobile version now since it is a software that is
on user end to give them and use in their own way

**Comment by lakshyabatman** [comment]
Ok, then this issue is useless, Should I close it? @jaskirat2000

**Comment by jaskirat2000** [comment]
Sure

**Comment by lakshyabatman** [comment]
I am reopening this issue, as I tested and found out that the scroll bar doesn't come for smaller browser size.
I think, even it just made for laptop and other large screen devices, there should be responsiveness in it which is also our first priority of this project.

**Comment by iamgrawal** [comment]
then I think @lakshyabatman, you should work on #68, since that issue specifies the same motive as to what you are saying for making it responsive.

**Comment by lakshyabatman** [comment]
ok, I will see to it or if someone else is willing to work on it, they can
