### ISSUE TITLE
Login Page For Organisation

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/Social-Platform-Donut#98]
While integrating the backend with frontend with the help of @capedcrusader23 , I found out there is no login page for Organisations although there exist one page for Signup named,  
<code>signup_community.html</code>
But not for login.

**Comment by jaskirat2000** [comment]
Thanks

**Comment by shakti97** [comment]
can i proceed and build it?
 @jaskirat2000

**Comment by sarthak77** [comment]
@jaskirat2000 can I take this one ?
